#!/usr/bin/env python3
"""Example using pre-compiled/embedded schema modules.

This approach uses the generated Python modules with embedded compiled
schemas. The modules are generated by the capnp-stub-generator and contain
base64-encoded schema data that is loaded at import time.

The generated modules automatically share a SchemaLoader (via capnp._embedded_schema_loader)
so capabilities work correctly across different schema modules.

Usage:
    # Run from the repository root:
    python tests/schemas/examples/registry/registry_with_embedded.py

Note: This example imports from tests/_generated/zalfmas which contains
the generated modules with embedded schemas.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

# Add the generated modules to the path
GENERATED_DIR = Path(__file__).parent.parent.parent.parent / "_generated" / "zalfmas"
sys.path.insert(0, str(GENERATED_DIR))

import capnp  # noqa: E402

# Import using embedded schema modules (generated by capnp-stub-generator)
from tests._generated.zalfmas.mas.schema.common import common_capnp  # noqa: E402
from tests._generated.zalfmas.mas.schema.registry import registry_capnp  # noqa: E402


class Identifiable(common_capnp.Identifiable.Server):
    """Server implementation of Identifiable interface."""

    async def info(self, _context, **kwargs) -> None:
        """Return id information."""


async def main() -> None:
    """Create a Registry.Entry message with an Identifiable capability."""
    re = registry_capnp.Registry.Entry.new_message(
        categoryId="cat",
        ref=Identifiable(),
        id="some_id",
        name="some_name",
    )
    print(f"Created Registry.Entry: {re}")
    print(f"  categoryId: {re.categoryId}")
    print(f"  id: {re.id}")
    print(f"  name: {re.name}")


if __name__ == "__main__":
    asyncio.run(capnp.run(main()))
