"""Client helper types for `restorer.capnp`."""

from capnp.lib.capnp import (
    _DynamicCapabilityClient,
)

from . import common as common
from . import requests as requests
from .results import client as results_client

class BagClient(_DynamicCapabilityClient):
    def getValue(self) -> results_client.GetvalueResult: ...
    def setValue(self, value: str | None = None) -> results_client.SetvalueResult: ...
    def getValue_request(self) -> requests.GetvalueRequest: ...
    def setValue_request(self, value: str | None = None) -> requests.SetvalueRequest: ...

class AnyTesterClient(_DynamicCapabilityClient):
    def getAnyStruct(self) -> results_client.GetanystructResult: ...
    def getAnyList(self) -> results_client.GetanylistResult: ...
    def getAnyPointer(self) -> results_client.GetanypointerResult: ...
    def setAnyPointer(self, p: common.AnyPointer | None = None) -> results_client.SetanypointerResult: ...
    def getAnyStruct_request(self) -> requests.GetanystructRequest: ...
    def getAnyList_request(self) -> requests.GetanylistRequest: ...
    def getAnyPointer_request(self) -> requests.GetanypointerRequest: ...
    def setAnyPointer_request(self, p: common.AnyPointer | None = None) -> requests.SetanypointerRequest: ...

class RestorerClient(_DynamicCapabilityClient):
    def restore(self, localRef: str | None = None) -> results_client.RestoreResult: ...
    def getAnyTester(self) -> results_client.GetanytesterResult: ...
    def restore_request(self, localRef: str | None = None) -> requests.RestoreRequest: ...
    def getAnyTester_request(self) -> requests.GetanytesterRequest: ...
