"""Client helper types for `single_value.capnp`."""

from capnp.lib.capnp import (
    _DynamicCapabilityClient,
)

from . import requests as requests
from .results import client as results_client

class SingleValueClient(_DynamicCapabilityClient):
    def getBool(self) -> results_client.GetboolResult: ...
    def getInt(self) -> results_client.GetintResult: ...
    def getFloat(self) -> results_client.GetfloatResult: ...
    def getText(self) -> results_client.GettextResult: ...
    def getData(self) -> results_client.GetdataResult: ...
    def getList(self) -> results_client.GetlistResult: ...
    def getStruct(self) -> results_client.GetstructResult: ...
    def getInterface(self) -> results_client.GetinterfaceResult: ...
    def getAny(self) -> results_client.GetanyResult: ...
    def getListStruct(self) -> results_client.GetliststructResult: ...
    def getBool_request(self) -> requests.GetboolRequest: ...
    def getInt_request(self) -> requests.GetintRequest: ...
    def getFloat_request(self) -> requests.GetfloatRequest: ...
    def getText_request(self) -> requests.GettextRequest: ...
    def getData_request(self) -> requests.GetdataRequest: ...
    def getList_request(self) -> requests.GetlistRequest: ...
    def getStruct_request(self) -> requests.GetstructRequest: ...
    def getInterface_request(self) -> requests.GetinterfaceRequest: ...
    def getAny_request(self) -> requests.GetanyRequest: ...
    def getListStruct_request(self) -> requests.GetliststructRequest: ...
