"""Builder helper types for `addressbook.capnp`."""

from typing import Any, Literal, overload, override

from capnp.lib.capnp import (
    _DynamicStructBuilder,
)

from . import enums as enums
from . import lists as lists
from . import readers as readers

class PhoneNumberBuilder(_DynamicStructBuilder):
    @property
    def number(self) -> str: ...
    @number.setter
    def number(self, value: str) -> None: ...
    @property
    def type(self) -> enums.PersonPhoneNumberTypeEnum: ...
    @type.setter
    def type(self, value: enums.PersonPhoneNumberTypeEnum) -> None: ...
    @override
    def as_reader(self) -> readers.PhoneNumberReader: ...

class PersonEmploymentBuilder(_DynamicStructBuilder):
    @property
    def unemployed(self) -> None: ...
    @unemployed.setter
    def unemployed(self, value: None) -> None: ...
    @property
    def employer(self) -> str: ...
    @employer.setter
    def employer(self, value: str) -> None: ...
    @property
    def school(self) -> str: ...
    @school.setter
    def school(self, value: str) -> None: ...
    @property
    def selfEmployed(self) -> None: ...
    @selfEmployed.setter
    def selfEmployed(self, value: None) -> None: ...
    @override
    def which(self) -> Literal["unemployed", "employer", "school", "selfEmployed"]: ...
    @override
    def as_reader(self) -> readers.PersonEmploymentReader: ...

class PersonTestGroupBuilder(_DynamicStructBuilder):
    @property
    def field1(self) -> int: ...
    @field1.setter
    def field1(self, value: int) -> None: ...
    @property
    def field2(self) -> int: ...
    @field2.setter
    def field2(self, value: int) -> None: ...
    @property
    def field3(self) -> int: ...
    @field3.setter
    def field3(self, value: int) -> None: ...
    @override
    def as_reader(self) -> readers.PersonTestGroupReader: ...

class PersonBuilder(_DynamicStructBuilder):
    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, value: int) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def email(self) -> str: ...
    @email.setter
    def email(self, value: str) -> None: ...
    @property
    def phones(self) -> PhoneNumberListBuilder: ...
    @phones.setter
    def phones(self, value: PhoneNumberListBuilder | readers.PhoneNumberListReader | dict[str, Any]) -> None: ...
    @property
    def employment(self) -> PersonEmploymentBuilder: ...
    @employment.setter
    def employment(self, value: PersonEmploymentBuilder | readers.PersonEmploymentReader | dict[str, Any]) -> None: ...
    @property
    def testGroup(self) -> PersonTestGroupBuilder: ...
    @testGroup.setter
    def testGroup(self, value: PersonTestGroupBuilder | readers.PersonTestGroupReader | dict[str, Any]) -> None: ...
    @property
    def extraData(self) -> bytes: ...
    @extraData.setter
    def extraData(self, value: bytes) -> None: ...
    @override
    @overload
    def init(self, field: Literal["employment"], size: int | None = None) -> PersonEmploymentBuilder: ...
    @overload
    def init(self, field: Literal["testGroup"], size: int | None = None) -> PersonTestGroupBuilder: ...
    @overload
    def init(self, field: Literal["phones"], size: int | None = None) -> PhoneNumberListBuilder: ...
    @overload
    def init(self, field: str, size: int | None = None) -> Any: ...
    @override
    def as_reader(self) -> readers.PersonReader: ...

class AddressBookBuilder(_DynamicStructBuilder):
    @property
    def people(self) -> PersonListBuilder: ...
    @people.setter
    def people(self, value: PersonListBuilder | readers.PersonListReader | dict[str, Any]) -> None: ...
    @override
    def init(self, field: Literal["people"], size: int | None = None) -> PersonListBuilder: ...
    @override
    def as_reader(self) -> readers.AddressBookReader: ...

type PersonListBuilder = lists._PersonList.Builder

type PhoneNumberListBuilder = lists._PhoneNumberList.Builder
