"""Builder helper types for `fbp_nested_callback.capnp`."""

from typing import override

from capnp.lib.capnp import (
    _DynamicStructBuilder,
)

from . import readers as readers

class StatsBuilder(_DynamicStructBuilder):
    @property
    def noOfWaitingWriters(self) -> int: ...
    @noOfWaitingWriters.setter
    def noOfWaitingWriters(self, value: int) -> None: ...
    @property
    def noOfWaitingReaders(self) -> int: ...
    @noOfWaitingReaders.setter
    def noOfWaitingReaders(self, value: int) -> None: ...
    @property
    def noOfIpsInQueue(self) -> int: ...
    @noOfIpsInQueue.setter
    def noOfIpsInQueue(self, value: int) -> None: ...
    @property
    def totalNoOfIpsReceived(self) -> int: ...
    @totalNoOfIpsReceived.setter
    def totalNoOfIpsReceived(self, value: int) -> None: ...
    @property
    def timestamp(self) -> str: ...
    @timestamp.setter
    def timestamp(self, value: str) -> None: ...
    @property
    def updateIntervalInMs(self) -> int: ...
    @updateIntervalInMs.setter
    def updateIntervalInMs(self, value: int) -> None: ...
    @override
    def as_reader(self) -> readers.StatsReader: ...
